### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by teneresa** [Simranjitk/radar-ionic#1]
Hi, my name is Valeria. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your app. If it's something you're interested in, please, let me know!
Best,
Valeria

**Comment by Simranjitk** [comment]
@teneresa Hi Valeria, that would be great if you have any ideas for an icon design for the plugin.

**Comment by teneresa** [comment]
Glad to hear this! And how do you plan to use the icon? On your website, GitHub page, Google Play Store, etc..

**Comment by Simranjitk** [comment]
Hi, the logo would be simply for the github page for the plugin.

**Comment by teneresa** [comment]
Hi Simranjit, I made some options. please have a look! 

![radar logo-01](https://user-images.githubusercontent.com/39339824/42473176-464a8e1a-839a-11e8-9b99-7ebbef962a15.jpg)

All of them can be used with the text as a logo and without text as an icon. Let me know which one do you like most or if it requires any additional changes!

**Comment by Simranjitk** [comment]
All of the logos are very nice! I especially like 3a. We can display that one on the Github page and give you credit for it!

**Comment by teneresa** [comment]
Glad to hear this! The design is free for you and I’m happy that you like it. I’ll prepare all the required files and create a pull-request.

**Comment by teneresa** [comment]
Simranjit, I uploaded logo files and created a pull-request, please merge it! If you need any other file formats, you can download them [here](https://drive.google.com/open?id=17VH0a8i2xHGYSVPSCoLlubsgivqdY4G9) from my Google Drive :)

**Comment by Simranjitk** [comment]
Awesome work!! Thanks for the addition.
